<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'designer_id' => 1,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Technico 1',
                'serie_name' => 'Technico',
                'picture' => 'https://images.kunstveiling.be/tmp-de5542f2e219b01f00fc5e1eea35cfd8-bob-kemper_d700.jpeg',
                'description' => 'Eerste van vier abstracte zeefdrukken met als onderwerp techniek in de jaren negentig.',
                'price' => 19.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Technico 2',
                'serie_name' => 'Technico',
                'picture' => 'https://images.kunstveiling.be/tmp-285264e866b5c397fd51f5f92754baa6-bob-kemper_d700.jpeg',
                'description' => 'Tweede van vier abstracte zeefdrukken met als onderwerp techniek in de jaren negentig.',
                'price' => 19.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Technico 3',
                'serie_name' => 'Technico',
                'picture' => 'https://images.kunstveiling.be/tmp-b144803bcd0b55d6ca10f383383be096-bob-kemper_d700.jpeg',
                'description' => 'Derde van vier abstracte zeefdrukken met als onderwerp techniek in de jaren negentig.',
                'price' => 19.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Technico 4',
                'serie_name' => 'Technico',
                'picture' => 'https://images.kunstveiling.be/tmp-fa3c4c1629ae8fc8611b7e862cd15bb7-bob-kemper_d700.jpeg',
                'description' => 'Vierde van vier abstracte zeefdrukken met als onderwerp techniek in de jaren negentig.',
                'price' => 19.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Warhol 1',
                'serie_name' => 'Warhol',
                'picture' => 'https://images.kunstveiling.nl/tmp-81b7d7cc52822d482fd83446384fc4be-rosenthal_d2600.jpeg',
                'description' => 'Eerste van een portret van Andy Warhol op glasplaat.',
                'price' => 24.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Warhol 2',
                'serie_name' => 'Warhol',
                'picture' => 'https://images.kunstveiling.nl/tmp-d0cf31c3dea8f6f807b7467a298af859-rosenthal_d2600.jpeg',
                'description' => 'Tweede van een portret van Andy Warhol op glasplaat.',
                'price' => 24.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Warhol 3',
                'serie_name' => 'Warhol',
                'picture' => 'https://images.kunstveiling.nl/tmp-31b5ce880a0d6121e270df067feccf71-rosenthal_d2600.jpeg',
                'description' => 'Derde van een portret van Andy Warhol op glasplaat.',
                'price' => 24.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Warhol 4',
                'serie_name' => 'Warhol',
                'picture' => 'https://images.kunstveiling.nl/tmp-ecf0625343d085d9c4f2b038213c639e-rosenthal_d2600.jpeg',
                'description' => 'Vierde van een portret van Andy Warhol op glasplaat.',
                'price' => 24.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Mona Lisa 1',
                'serie_name' => 'Mona-Lisa',
                'picture' => 'https://www.artyfactory.com/portraits/pop-art-portraits/images/mona_lisa_color_bak.jpg',
                'description' => 'Mona Lisa in primaire en secundaire kleuren.',
                'price' => 16.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Mona Lisa 2',
                'serie_name' => 'Mona-Lisa',
                'picture' => 'https://www.artyfactory.com/portraits/pop-art-portraits/images/mona_lisa_6.jpg',
                'description' => 'Mona Lisa opgevuld met patronen.',
                'price' => 16.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Mona Lisa 3',
                'serie_name' => 'Mona-Lisa',
                'picture' => 'https://www.artyfactory.com/portraits/pop-art-portraits/images/mona_lisa_5.jpg',
                'description' => 'Mona Lisa met graduële effecten.',
                'price' => 16.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Mona Lisa 4',
                'serie_name' => 'Mona-Lisa',
                'picture' => 'https://www.artyfactory.com/portraits/pop-art-portraits/images/mona_lisa_14.jpg',
                'description' => 'Mona Lisa met in elkaar overlopende schaduwen.',
                'price' => 16.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Warhol Tomato soup',
                'serie_name' => 'Warhol-cans',
                'picture' => 'https://www.christies.com/img/LotImages/2010/NYR/2010_NYR_02355_0012_000(andy_warhol_campbells_soup_can103047).jpg',
                'description' => 'Andy Warhol zijn beroemde soepblikken, variant tomaat.',
                'price' => 14.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Warhol Pepper pot soup',
                'serie_name' => 'Warhol-cans',
                'picture' => 'https://media.vanityfair.com/photos/5bdcbde1adbbcc502c0039c3/master/w_1600%2Cc_limit/warhol-campbell-cans-dec-2018-embed01.png',
                'description' => 'Andy Warhol zijn beroemde soepblikken, variant peper.',
                'price' => 14.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Warhol Onion soup',
                'serie_name' => 'Warhol-cans',
                'picture' => 'https://www.guyhepner.com/wp-content/uploads/2015/04/Onion-.png',
                'description' => 'Andy Warhol zijn beroemde soepblikken, variant ui.',
                'price' => 14.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Warhol Cheddar Cheese Soup',
                'serie_name' => 'Warhol-cans',
                'picture' => 'https://www.dertnijlandfinearts.nl/images/productimages/small/warhol-campbell-cheddar-0.jpg',
                'description' => 'Andy Warhol zijn beroemde soepblikken, variant cheddar-kaas.',
                'price' => 14.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 3,
                'shippingclass_id' => 2,
                'product_name' => 'Kathedraal bij zonsondergang',
                'serie_name' => 'Monet',
                'picture' => 'https://kunstblik.files.wordpress.com/2017/12/claude_monet-rouen_cathedral_sunset.jpg?w=700&h=',
                'description' => 'Dertig keer schilderde Monet de kathedraal van Rouen om de invloed van licht te vangen, in dit geval bij zonsondergang.',
                'price' => 12.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 3,
                'shippingclass_id' => 2,
                'product_name' => 'Kathedraal bij avondlicht.',
                'serie_name' => 'Monet',
                'picture' => 'https://kunstblik.files.wordpress.com/2017/12/claude_monet-rouen_cathedral_facade_i.jpg?w=700&h=',
                'description' => 'Dertig keer schilderde Monet de kathedraal van Rouen om de invloed van licht te vangen, in dit geval in het avondlicht..',
                'price' => 12.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 3,
                'shippingclass_id' => 2,
                'product_name' => 'Kathedraal in de volle zon.',
                'serie_name' => 'Monet',
                'picture' => 'https://kunstblik.files.wordpress.com/2017/12/claude_monet-rouen_cathedral.jpg?w=700&h=',
                'description' => 'Dertig keer schilderde Monet de kathedraal van Rouen om de invloed van licht te vangen, in dit geval in de volle zon.',
                'price' => 12.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 3,
                'shippingclass_id' => 2,
                'product_name' => 'Kathedraal in ochtendlicht.',
                'serie_name' => 'Monet',
                'picture' => 'https://kunstblik.files.wordpress.com/2017/12/claude_monet-rouen_cathedral_matin.jpeg?w=700&h=',
                'description' => 'Dertig keer schilderde Monet de kathedraal van Rouen om de invloed van licht te vangen, in dit geval in ochtendlicht.',
                'price' => 12.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 4,
                'shippingclass_id' => 2,
                'product_name' => 'Compositie VII',
                'serie_name' => 'Kandinsky',
                'picture' => 'https://kunstblik.files.wordpress.com/2018/05/kandinsky-compositie-vii.jpg?w=1200&h=',
                'description' => 'Tien composities van Kandinsky, volgens hem zelf de belangrijkste schilderijen uit zijn oeuvre.',
                'price' => 17.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 4,
                'shippingclass_id' => 2,
                'product_name' => 'Compositie VIII',
                'serie_name' => 'Kandinsky',
                'picture' => 'https://kunstblik.files.wordpress.com/2018/05/kandinsky-compositie-viii.jpg?w=1200&h=',
                'description' => 'Tien composities van Kandinsky, volgens hem zelf de belangrijkste schilderijen uit zijn oeuvre.',
                'price' => 17.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 4,
                'shippingclass_id' => 2,
                'product_name' => 'Compositie IX',
                'serie_name' => 'Kandinsky',
                'picture' => 'https://kunstblik.files.wordpress.com/2018/05/kandinsky-compositie-ix.jpg',
                'description' => 'Tien composities van Kandinsky, volgens hem zelf de belangrijkste schilderijen uit zijn oeuvre.',
                'price' => 17.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 4,
                'shippingclass_id' => 2,
                'product_name' => 'Compositie X',
                'serie_name' => 'Kandinsky',
                'picture' => 'https://kunstblik.files.wordpress.com/2018/05/kandinsky-compositie-x.jpg?w=1200&h=',
                'description' => 'Tien composities van Kandinsky, volgens hem zelf de belangrijkste schilderijen uit zijn oeuvre.',
                'price' => 17.95,
                'created_by' => 3,
            ],
        ]);
    }
}
