<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'designer_id' => 1,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Technico 1',
                'serie_name' => 'Technico',
                'picture' => 'https://images.kunstveiling.be/tmp-de5542f2e219b01f00fc5e1eea35cfd8-bob-kemper_d700.jpeg',
                'description' => 'Eerste van vier abstracte zeefdrukken met als onderwerp techniek in de jaren negentig.',
                'price' => 19.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Technico 2',
                'serie_name' => 'Technico',
                'picture' => 'https://images.kunstveiling.be/tmp-285264e866b5c397fd51f5f92754baa6-bob-kemper_d700.jpeg',
                'description' => 'Tweede van vier abstracte zeefdrukken met als onderwerp techniek in de jaren negentig.',
                'price' => 19.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Technico 3',
                'serie_name' => 'Technico',
                'picture' => 'https://images.kunstveiling.be/tmp-b144803bcd0b55d6ca10f383383be096-bob-kemper_d700.jpeg',
                'description' => 'Derde van vier abstracte zeefdrukken met als onderwerp techniek in de jaren negentig.',
                'price' => 19.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Technico 4',
                'serie_name' => 'Technico',
                'picture' => 'https://images.kunstveiling.be/tmp-fa3c4c1629ae8fc8611b7e862cd15bb7-bob-kemper_d700.jpeg',
                'description' => 'Vierde van vier abstracte zeefdrukken met als onderwerp techniek in de jaren negentig.',
                'price' => 19.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Warhol 1',
                'serie_name' => 'Warhol',
                'picture' => 'https://images.kunstveiling.nl/tmp-81b7d7cc52822d482fd83446384fc4be-rosenthal_d2600.jpeg',
                'description' => 'Eerste van een portret van Andy Warhol op glasplaat.',
                'price' => 24.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Warhol 2',
                'serie_name' => 'Warhol',
                'picture' => 'https://images.kunstveiling.nl/tmp-d0cf31c3dea8f6f807b7467a298af859-rosenthal_d2600.jpeg',
                'description' => 'Tweede van een portret van Andy Warhol op glasplaat.',
                'price' => 24.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Warhol 3',
                'serie_name' => 'Warhol',
                'picture' => 'https://images.kunstveiling.nl/tmp-31b5ce880a0d6121e270df067feccf71-rosenthal_d2600.jpeg',
                'description' => 'Derde van een portret van Andy Warhol op glasplaat.',
                'price' => 24.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Warhol 4',
                'serie_name' => 'Warhol',
                'picture' => 'https://images.kunstveiling.nl/tmp-ecf0625343d085d9c4f2b038213c639e-rosenthal_d2600.jpeg',
                'description' => 'Vierde van een portret van Andy Warhol op glasplaat.',
                'price' => 24.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Mona Lisa 1',
                'serie_name' => 'Mona-Lisa',
                'picture' => 'https://www.artyfactory.com/portraits/pop-art-portraits/images/mona_lisa_color_bak.jpg',
                'description' => 'Mona Lisa in primaire en secundaire kleuren.',
                'price' => 16.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Mona Lisa 2',
                'serie_name' => 'Mona-Lisa',
                'picture' => 'https://www.artyfactory.com/portraits/pop-art-portraits/images/mona_lisa_6.jpg',
                'description' => 'Mona Lisa opgevuld met patronen.',
                'price' => 16.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Mona Lisa 3',
                'serie_name' => 'Mona-Lisa',
                'picture' => 'https://www.artyfactory.com/portraits/pop-art-portraits/images/mona_lisa_5.jpg',
                'description' => 'Mona Lisa met graduële effecten.',
                'price' => 16.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Mona Lisa 4',
                'serie_name' => 'Mona-Lisa',
                'picture' => 'https://www.artyfactory.com/portraits/pop-art-portraits/images/mona_lisa_14.jpg',
                'description' => 'Mona Lisa met in elkaar overlopende schaduwen.',
                'price' => 16.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Warhol Tomato soup',
                'serie_name' => 'Warhol-cans',
                'picture' => 'https://www.christies.com/img/LotImages/2010/NYR/2010_NYR_02355_0012_000(andy_warhol_campbells_soup_can103047).jpg',
                'description' => 'Andy Warhol zijn beroemde soepblikken, variant tomaat.',
                'price' => 14.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Warhol Pepper pot soup',
                'serie_name' => 'Warhol-cans',
                'picture' => 'https://media.vanityfair.com/photos/5bdcbde1adbbcc502c0039c3/master/w_1600%2Cc_limit/warhol-campbell-cans-dec-2018-embed01.png',
                'description' => 'Andy Warhol zijn beroemde soepblikken, variant peper.',
                'price' => 14.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Warhol Onion soup',
                'serie_name' => 'Warhol-cans',
                'picture' => 'https://www.guyhepner.com/wp-content/uploads/2015/04/Onion-.png',
                'description' => 'Andy Warhol zijn beroemde soepblikken, variant ui.',
                'price' => 14.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Warhol Cheddar Cheese Soup',
                'serie_name' => 'Warhol-cans',
                'picture' => 'https://www.dertnijlandfinearts.nl/images/productimages/small/warhol-campbell-cheddar-0.jpg',
                'description' => 'Andy Warhol zijn beroemde soepblikken, variant cheddar-kaas.',
                'price' => 14.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 3,
                'shippingclass_id' => 2,
                'product_name' => 'Kathedraal bij zonsondergang',
                'serie_name' => 'Monet',
                'picture' => 'https://kunstblik.files.wordpress.com/2017/12/claude_monet-rouen_cathedral_sunset.jpg?w=700&h=',
                'description' => 'Dertig keer schilderde Monet de kathedraal van Rouen om de invloed van licht te vangen, in dit geval bij zonsondergang.',
                'price' => 12.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 3,
                'shippingclass_id' => 2,
                'product_name' => 'Kathedraal bij avondlicht.',
                'serie_name' => 'Monet',
                'picture' => 'https://kunstblik.files.wordpress.com/2017/12/claude_monet-rouen_cathedral_facade_i.jpg?w=700&h=',
                'description' => 'Dertig keer schilderde Monet de kathedraal van Rouen om de invloed van licht te vangen, in dit geval in het avondlicht..',
                'price' => 12.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 3,
                'shippingclass_id' => 2,
                'product_name' => 'Kathedraal in de volle zon.',
                'serie_name' => 'Monet',
                'picture' => 'https://kunstblik.files.wordpress.com/2017/12/claude_monet-rouen_cathedral.jpg?w=700&h=',
                'description' => 'Dertig keer schilderde Monet de kathedraal van Rouen om de invloed van licht te vangen, in dit geval in de volle zon.',
                'price' => 12.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 3,
                'shippingclass_id' => 2,
                'product_name' => 'Kathedraal in ochtendlicht.',
                'serie_name' => 'Monet',
                'picture' => 'https://kunstblik.files.wordpress.com/2017/12/claude_monet-rouen_cathedral_matin.jpeg?w=700&h=',
                'description' => 'Dertig keer schilderde Monet de kathedraal van Rouen om de invloed van licht te vangen, in dit geval in ochtendlicht.',
                'price' => 12.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 4,
                'shippingclass_id' => 2,
                'product_name' => 'Compositie VII',
                'serie_name' => 'Kandinsky',
                'picture' => 'https://kunstblik.files.wordpress.com/2018/05/kandinsky-compositie-vii.jpg?w=1200&h=',
                'description' => 'Tien composities van Kandinsky, volgens hem zelf de belangrijkste schilderijen uit zijn oeuvre.',
                'price' => 17.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 4,
                'shippingclass_id' => 2,
                'product_name' => 'Compositie VIII',
                'serie_name' => 'Kandinsky',
                'picture' => 'https://kunstblik.files.wordpress.com/2018/05/kandinsky-compositie-viii.jpg?w=1200&h=',
                'description' => 'Tien composities van Kandinsky, volgens hem zelf de belangrijkste schilderijen uit zijn oeuvre.',
                'price' => 17.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 4,
                'shippingclass_id' => 2,
                'product_name' => 'Compositie IX',
                'serie_name' => 'Kandinsky',
                'picture' => 'https://kunstblik.files.wordpress.com/2018/05/kandinsky-compositie-ix.jpg',
                'description' => 'Tien composities van Kandinsky, volgens hem zelf de belangrijkste schilderijen uit zijn oeuvre.',
                'price' => 17.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 4,
                'shippingclass_id' => 2,
                'product_name' => 'Compositie X',
                'serie_name' => 'Kandinsky',
                'picture' => 'https://kunstblik.files.wordpress.com/2018/05/kandinsky-compositie-x.jpg?w=1200&h=',
                'description' => 'Tien composities van Kandinsky, volgens hem zelf de belangrijkste schilderijen uit zijn oeuvre.',
                'price' => 17.95,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Boiling Bubbles Original',
                'serie_name' => 'Bubbels',
                'picture' => 'https://ronaldhunter.com/wp-content/uploads/large_abstract_painting_modern_artwork_original_front-150x150.jpg',
                'description' => '
                Snelle penseelstreken creëren een gevoel van beweging, van positieve energie die vrij rondstroomt. Dit prachtige abstracte schilderij is gemaakt met vele lagen acrylverf waardoor er diepte en textuur ontstaat.',
                'price' => 26.49,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Boiling Bubbles Light in Red',
                'serie_name' => 'Bubbels',
                'picture' => 'https://ronaldhunter.com/wp-content/uploads/red_acrylic_painting_vertical_abstract_art_front-150x150.jpg',
                'description' => '
                Snelle penseelstreken creëren een gevoel van beweging, van positieve energie die vrij rondstroomt. Dit prachtige abstracte schilderij is gemaakt met vele lagen acrylverf waardoor er diepte en textuur ontstaat.',
                'price' => 26.49,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Boiling Bubbles Turquoise',
                'serie_name' => 'Bubbels',
                'picture' => 'https://ronaldhunter.com/wp-content/uploads/turquoise_painting_abstract_colorful_art_ronald_hunter-3-150x150.jpg',
                'description' => '
                Snelle penseelstreken creëren een gevoel van beweging, van positieve energie die vrij rondstroomt. Dit prachtige abstracte schilderij is gemaakt met vele lagen acrylverf waardoor er diepte en textuur ontstaat.',
                'price' => 26.49,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Boiling Bubbles Landscape',
                'serie_name' => 'Bubbels',
                'picture' => 'https://ronaldhunter.com/wp-content/uploads/turquoise_landscape_painting_abstract_ronald_hunter-5-1-150x150.jpg',
                'description' => '
                Snelle penseelstreken creëren een gevoel van beweging, van positieve energie die vrij rondstroomt. Dit prachtige abstracte schilderij is gemaakt met vele lagen acrylverf waardoor er diepte en textuur ontstaat.',
                'price' => 26.49,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Forum 1',
                'serie_name' => 'Keramiek-fantastiek',
                'picture' => 'https://michaelreid.com.au/wp-content/uploads/2020/12/Ceramics-Nov-2020-9-scaled-1160x1160.jpg',
                'description' => 'Geïnspireerd op het Groninger forum heb ik gewerkt met blauw en wit. Minder geschikt voor gezinnen, keramiek is breekbaar!',
                'price' => 29.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Forum 2',
                'serie_name' => 'Keramiek-fantastiek',
                'picture' => 'https://michaelreid.com.au/wp-content/uploads/2020/12/Ceramics-Nov-2020-18-scaled-1160x1160.jpg',
                'description' => 'Geïnspireerd op het Groninger forum heb ik gewerkt met blauw en wit. Minder geschikt voor gezinnen, keramiek is breekbaar!',
                'price' => 29.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Forum 3',
                'serie_name' => 'Keramiek-fantastiek',
                'picture' => 'https://michaelreid.com.au/wp-content/uploads/2020/12/Ceramics-Nov-2020-27-scaled-1160x1160.jpg',
                'description' => 'Geïnspireerd op het Groninger forum heb ik gewerkt met blauw en wit. Minder geschikt voor gezinnen, keramiek is breekbaar!',
                'price' => 29.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Forum 4',
                'serie_name' => 'Keramiek-fantastiek',
                'picture' => 'https://michaelreid.com.au/wp-content/uploads/2020/12/Ceramics-Nov-2020-40-1-scaled-1160x1160.jpg',
                'description' => 'Geïnspireerd op het Groninger forum heb ik gewerkt met blauw en wit. Minder geschikt voor gezinnen, keramiek is breekbaar!',
                'price' => 29.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Gekke Bek 1',
                'serie_name' => 'Messerschmidt',
                'picture' => 'https://kunstblik.files.wordpress.com/2020/06/messerschmidt4.jpg?w=700&h=',
                'description' => 'Deze karakterkoppen laten de uitersten van menselijke emoties zien.',
                'price' => 49.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Gekke Bek 2',
                'serie_name' => 'Messerschmidt',
                'picture' => 'https://kunstblik.files.wordpress.com/2020/06/messerschmidt3.jpg?w=700&h=',
                'description' => 'Deze karakterkoppen laten de uitersten van menselijke emoties zien.',
                'price' => 49.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Gekke Bek 3',
                'serie_name' => 'Messerschmidt',
                'picture' => 'https://kunstblik.files.wordpress.com/2020/06/messerschmidt2.jpg?w=700&h=',
                'description' => 'Deze karakterkoppen laten de uitersten van menselijke emoties zien.',
                'price' => 49.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Gekke Bek 4',
                'serie_name' => 'Messerschmidt',
                'picture' => 'https://kunstblik.files.wordpress.com/2020/06/messerschmidt.jpg?w=700&h=',
                'description' => 'Deze karakterkoppen laten de uitersten van menselijke emoties zien.',
                'price' => 49.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'A Splash',
                'serie_name' => 'Plons!',
                'picture' => 'https://d7hftxdivxxvm.cloudfront.net/?resize_to=width&src=https%3A%2F%2Fartsy-media-uploads.s3.amazonaws.com%2FYbAM08KgahH-RJeSJBPwww%252FDavid%2BHockney%252C%2BThe%2BSplash%252C%2B1966%2B%2528hi-res%2529%2Bcropped.jpg&width=1200&quality=80',
                'description' => 'Iconsische pop-art met duikplank. Leuk voor aan de muur en niet duur.',
                'price' => 9.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'A Bigger Splash',
                'serie_name' => 'Plons!',
                'picture' => 'https://www.tate.org.uk/art/images/work/T/T03/T03254_10.jpg',
                'description' => 'Iconsische pop-art met duikplank. Leuk voor aan de muur en niet duur.',
                'price' => 9.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'The Little Splash',
                'serie_name' => 'Plons!',
                'picture' => 'https://i.ebayimg.com/images/g/-WEAAOSw6aJcwoCg/s-l1600.jpg',
                'description' => 'Iconsische pop-art met duikplank. Leuk voor aan de muur en niet duur.',
                'price' => 9.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 2,
                'shippingclass_id' => 2,
                'product_name' => 'Pool with two figures',
                'serie_name' => 'Plons!',
                'picture' => 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a5/Hockney_Pool_Figures.jpg/365px-Hockney_Pool_Figures.jpg',
                'description' => 'Iconsische pop-art met duikplank. Leuk voor aan de muur en niet duur.',
                'price' => 9.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Penseelstreek rood',
                'serie_name' => 'Brushstrokes',
                'picture' => 'https://blog.singulart.com/wp-content/uploads/2019/11/roy-lichtenstein-brushstrokes-1965.jpg',
                'description' => 'Kunst als handeling, dat drukken deze posters uit. Vanwege de massaproductie zijn de kosten laag gehouden.',
                'price' => 6.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Penseelstreek geel',
                'serie_name' => 'Brushstrokes',
                'picture' => 'https://www.tate.org.uk/art/images/work/P/P07/P07354_10.jpg',
                'description' => 'Kunst als handeling, dat drukken deze posters uit. Vanwege de massaproductie zijn de kosten laag gehouden.',
                'price' => 6.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Penseelstreek rood met wit',
                'serie_name' => 'Brushstrokes',
                'picture' => 'https://www.christies.com/media-library/images/features/articles/2017/04/21/lichtenstein-brushstroke/roy-lichtenstein-red-and-white-brushstrokes.jpg?w=780',
                'description' => 'Kunst als handeling, dat drukken deze posters uit. Vanwege de massaproductie zijn de kosten laag gehouden.',
                'price' => 6.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Penseelstreek rood, wit én geel',
                'serie_name' => 'Brushstrokes',
                'picture' => 'https://www.guyhepner.com/wp-content/uploads/2016/06/Reflections-On-Brushtroke-by-Roy-Licthenstein.png',
                'description' => 'Kunst als handeling, dat drukken deze posters uit. Vanwege de massaproductie zijn de kosten laag gehouden.',
                'price' => 6.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Montmartre in de zon',
                'serie_name' => 'Montmartre',
                'picture' => 'https://impressionistarts.com/assets/camille-pissarro-boulevard-montmartre-sunny-afternoon.jpg',
                'description' => 'Voor deze opdracht heb ik Pissaro als inspiratie genomen. De techniek die ik heb gebruikt is plagiëren.',
                'price' => 17.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Montmartre in de mist',
                'serie_name' => 'Montmartre',
                'picture' => 'https://impressionistarts.com/assets/camille-pissarro-boulevard-montmartre-foggy-morning.jpg',
                'description' => 'Voor deze opdracht heb ik Pissaro als inspiratie genomen. De techniek die ik heb gebruikt is plagiëren.',
                'price' => 17.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Montmartre in de lenteregen',
                'serie_name' => 'Montmartre',
                'picture' => 'https://impressionistarts.com/assets/camille-pissarro-boulevard-montmartre-spring-rain.jpg',
                'description' => 'Voor deze opdracht heb ik Pissaro als inspiratie genomen. De techniek die ik heb gebruikt is plagiëren.',
                'price' => 17.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Montmartre bij nacht',
                'serie_name' => 'Montmartre',
                'picture' => 'https://impressionistarts.com/assets/camille-pissarro-boulevard-montmartre-at-night.jpg',
                'description' => 'Voor deze opdracht heb ik Pissaro als inspiratie genomen. De techniek die ik heb gebruikt is plagiëren.',
                'price' => 17.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'De Berg met een pijnboom',
                'serie_name' => 'Mont-Sainte-Victoire',
                'picture' => 'https://drawpaintacademy.com/wp-content/uploads/2019/03/Paul-Ce%CC%81zanne-Mont-Sainte-Victoire-with-Large-Pine-Around-1887-2.jpg',
                'description' => 'Paul Cézanne, de man die alles kan, ving het veranderlijke licht op zijn geliefde berg in een serie schilderijen. Dit zijn geen posters, maar echt canvas met lijst dus het kost wel wat.',
                'price' => 41.50,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'De Berg warm-koud',
                'serie_name' => 'Mont-Sainte-Victoire',
                'picture' => 'https://drawpaintacademy.com/wp-content/uploads/2019/03/Paul-Ce%CC%81zanne-Montagne-Sainte-Victoire-1890-3.jpg',
                'description' => 'Paul Cézanne, de man die alles kan, ving het veranderlijke licht op zijn geliefde berg in een serie schilderijen. Dit zijn geen posters, maar echt canvas met lijst dus het kost wel wat.',
                'price' => 41.50,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'De Berg rijk-donker',
                'serie_name' => 'Mont-Sainte-Victoire',
                'picture' => 'https://drawpaintacademy.com/wp-content/uploads/2019/03/Paul-Ce%CC%81zanne-Mont-Sainte-Victoire-and-Cha%CC%82teau-Noir-1904-1906-4.jpg',
                'description' => 'Paul Cézanne, de man die alles kan, ving het veranderlijke licht op zijn geliefde berg in een serie schilderijen. Dit zijn geen posters, maar echt canvas met lijst dus het kost wel wat.',
                'price' => 41.50,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'De Berg kubistisch',
                'serie_name' => 'Mont-Sainte-Victoire',
                'picture' => 'https://drawpaintacademy.com/wp-content/uploads/2019/03/Paul-C%C3%A9zanne-Mont-Sainte-Victoire-1902-04.jpg',
                'description' => 'Paul Cézanne, de man die alles kan, ving het veranderlijke licht op zijn geliefde berg in een serie schilderijen. Dit zijn geen posters, maar echt canvas met lijst dus het kost wel wat.',
                'price' => 41.50,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Zonnebloem met blauwgroen',
                'serie_name' => 'Zonnebloemen',
                'picture' => 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Vincent_Willem_van_Gogh_128.jpg',
                'description' => 'Net als Van Gogh heb ik besloten zonnebloemen te schilderen in olieverf, steeds tegen een andere achtergrond, afgedrukt als posters.',
                'price' => 7.50,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Zonnebloem met turqoise',
                'serie_name' => 'Zonnebloemen',
                'picture' => 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Vincent_Van_Gogh_-_Three_Sunflowers_F453.jpg',
                'description' => 'Net als Van Gogh heb ik besloten zonnebloemen te schilderen in olieverf, steeds tegen een andere achtergrond, afgedrukt als posters.',
                'price' => 7.50,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Zonnebloem met koningsblauw',
                'serie_name' => 'Zonnebloemen',
                'picture' => 'https://upload.wikimedia.org/wikipedia/commons/3/30/Six_Sunflowers_1888.jpg',
                'description' => 'Net als Van Gogh heb ik besloten zonnebloemen te schilderen in olieverf, steeds tegen een andere achtergrond, afgedrukt als posters.',
                'price' => 7.50,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 1,
                'shippingclass_id' => 2,
                'product_name' => 'Zonnebloem met geel',
                'serie_name' => 'Zonnebloemen',
                'picture' => 'https://upload.wikimedia.org/wikipedia/commons/4/46/Vincent_Willem_van_Gogh_127.jpg',
                'description' => 'Net als Van Gogh heb ik besloten zonnebloemen te schilderen in olieverf, steeds tegen een andere achtergrond, afgedrukt als posters.',
                'price' => 7.50,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 3,
                'shippingclass_id' => 2,
                'product_name' => 'Vorm met hoeken en kleuren',
                'serie_name' => 'Geometrievariaties',
                'picture' => 'http://www.artnet.com/WebServices/images/ll03690lld3JRJFgSUECiCfDrCWvaHBOc7ZJF/max-bill-quinze-variations-sur-un-m%C3%AAme-th%C3%A8me.jpg',
                'description' => 'Max Bill onderzocht de rotatie van een diamantvorm in combinatie met kleurbewegingen in vijftien variaties. Deze serie bestaat uit vier. Ingelijst in glas.',
                'price' => 18.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 3,
                'shippingclass_id' => 2,
                'product_name' => 'Vorm met cirkels en gekleurde punten',
                'serie_name' => 'Geometrievariaties',
                'picture' => 'https://d32dm0rphc51dk.cloudfront.net/hJhfIKIjU415ZSzTp1YpkA/large.jpg',
                'description' => 'Max Bill onderzocht de rotatie van een diamantvorm in combinatie met kleurbewegingen in vijftien variaties. Deze serie bestaat uit vier. Ingelijst in glas.',
                'price' => 18.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 3,
                'shippingclass_id' => 2,
                'product_name' => 'Vorm met dunne gekleurde cirkels',
                'serie_name' => 'Geometrievariaties',
                'picture' => 'https://s3-eu-central-1.amazonaws.com/germann-master/item_images/images/000/029/838/large/125645_1.jpg?1545306241',
                'description' => 'Max Bill onderzocht de rotatie van een diamantvorm in combinatie met kleurbewegingen in vijftien variaties. Deze serie bestaat uit vier. Ingelijst in glas.',
                'price' => 18.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 1,
                'collection_id' => 3,
                'shippingclass_id' => 2,
                'product_name' => 'Vorm met dikke gekleurde cirkels',
                'serie_name' => 'Geometrievariaties',
                'picture' => 'http://www.artnet.com/WebServices/images/ll03681lldY5VJFgSUECfDrCWvaHBOcoKjF/max-bill-quinze-variations-sur-un-m%C3%AAme-th%C3%A8me.jpg',
                'description' => 'Max Bill onderzocht de rotatie van een diamantvorm in combinatie met kleurbewegingen in vijftien variaties. Deze serie bestaat uit vier. Ingelijst in glas.',
                'price' => 18.99,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 4,
                'shippingclass_id' => 2,
                'product_name' => 'Warme vierkanten',
                'serie_name' => 'Vierkanten',
                'picture' => 'https://publicdelivery.b-cdn.net/wp-content/uploads/2019/02/Josef-Albers-Study-to-Homage-to-the-Square-Warm-Welcome-1953-1955-oil-on-Masonite-56-x-56-cm-800x801.jpg',
                'description' => 'Josef Albers hommage aan vierkanten lijkt eenvoudig, maar heeft de manier waarop kunstenaars kleur benaderen flink opgeschud. Deze serie van vier geeft daar een proeve van.',
                'price' => 11.25,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 4,
                'shippingclass_id' => 2,
                'product_name' => 'Herfstige vierkanten',
                'serie_name' => 'Vierkanten',
                'picture' => 'https://publicdelivery.b-cdn.net/wp-content/uploads/2019/02/Josef-Albers-Study-for-Homage-to-the-Square-Deep-Tune-1963-oil-on-masonite-76.3-x-76.3-cm-30-x-30-in-800x802.jpg',
                'description' => 'Josef Albers hommage aan vierkanten lijkt eenvoudig, maar heeft de manier waarop kunstenaars kleur benaderen flink opgeschud. Deze serie van vier geeft daar een proeve van.',
                'price' => 11.25,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 4,
                'shippingclass_id' => 2,
                'product_name' => 'Eendachtige vierkanten',
                'serie_name' => 'Vierkanten',
                'picture' => 'https://publicdelivery.b-cdn.net/wp-content/uploads/2019/02/Josef-Albers-Homage-to-the-Square-Ascending-1953-Oil-on-composition-board-110.3-%C3%97-110.3-cm-43-716-%C3%97-43-716-in.-800x800.jpg',
                'description' => 'Josef Albers hommage aan vierkanten lijkt eenvoudig, maar heeft de manier waarop kunstenaars kleur benaderen flink opgeschud. Deze serie van vier geeft daar een proeve van.',
                'price' => 11.25,
                'created_by' => 3,
            ],
            [
                'designer_id' => 2,
                'collection_id' => 4,
                'shippingclass_id' => 2,
                'product_name' => 'Midzomerse vierkanten',
                'serie_name' => 'Vierkanten',
                'picture' => 'https://publicdelivery.b-cdn.net/wp-content/uploads/2019/02/Josef-Albers-Homage-to-the-Square-Midsummer-1963-101.6-x-101.6-cm-40-x-40-in--800x803.jpg',
                'description' => 'Josef Albers hommage aan vierkanten lijkt eenvoudig, maar heeft de manier waarop kunstenaars kleur benaderen flink opgeschud. Deze serie van vier geeft daar een proeve van.',
                'price' => 11.25,
                'created_by' => 3,
            ],
        ]);
    }
}
